# docker-compose.yml
version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: kam-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: kam_leads_db
      POSTGRES_USER: kam_user
      POSTGRES_PASSWORD: kam_password
    volumes:
      - kam_pgdata:/var/lib/postgresql/data

volumes:
  kam_pgdata:
